### ISSUE TITLE
Parallel corpora in CQPweb

### ISSUE THREAD

**Issue by PhilBau** [chozelinek/paracorp#1]
Hi,
I am also trying to install parallel corpora in CQP.
I have successfully used your script to encode the corpora and to create the registry file.
Do you know if it's now possible to use it in CQPweb? and how?
Thank you for your help,
Philippe

**Comment by chozelinek** [comment]
Hi Philippe,

Glad to know that the script helped to encode the corpora. I've seen that you got answers in [CWB mailing list](http://devel.sslmit.unibo.it/pipermail/cwb/2016-April/002294.html) regarding this particular question. I think I will also try to use [ParaVoz2](https://bitbucket.org/rvwfels/paravoz2).

Best!

jmm
